### ISSUE TITLE
OAuthManager is undefined

### ISSUE THREAD

**Issue by davidpaulmcintyre** [fullstackreact/react-native-oauth#1]
I can't seem to get the constructor for OAuthManager to work.  I started with a vanilla react-native project initiated by "$ react-native init MyProject."  Then in installed react-native-oauth, and I tried both rnpm and the manual process for adding react-native-oauth to my Xcode project.  But in each case "const authManager = new OAuthManager()" results in an undefined error.  The app builds fine in Xcode, and I don't see any issues with the libraries.

I am familiar with React but not React-Native or iOS/Xcode.  I assume that the OAuthManager refers to a native library and therefore doesn't need to have an import or require statement at the top of my js file?  

Any help would be appreciated.

**Comment by davidpaulmcintyre** [comment]
it seems to be accessible with:
import { NativeModules } from 'react-native';
var mgr = NativeModules.OAuthManager;

is this now the proper way to access it?

**Comment by auser** [comment]
Oh no, that's the native module (apologies for the delay, I didn't see your issue until now). I'll be pushing an update here shortly.

**Comment by jvorcak** [comment]
@auser what is the proper way to access it? I've installed `react-native-oauth` and run `rnpm link` but I still can't figure out how to access it. The documentation says you should call OAuthManager but totally lacks the information where to get it from. Could you please help?

**Comment by auser** [comment]
Yep, I have a big update coming on the `feature/dctauth` branch that I'll merge when I finish Google auth.

**Comment by auser** [comment]
I have updated this completely and released a new version. Please pull the latest.

The README has been updated as well.

**Comment by julesmoretti** [comment]
@auser - Hello Auser: 

Unfortunately it is not working for me either. I am only interested in the Android version and following the Readme I get OAuthManager is not defined.

Note:
* I skipped all the IOS setup as I assume that those are not necessary to get the Android up and running
* I do not use any import OAuthManager as your readme does not include such information
* This is using a fresh `react-native init ...`

Let me know what I am missing please thank you :)

Thank you.

**Comment by julesmoretti** [comment]
@auser - Using `import OAuthManager from "react-native-oauth";` seems to work. 

Therefore please update readme if that is the right use case please :)

Thank you.
