### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by naiyt** [fullstackreact/react-native-oauth#10]
I'm working on implementing Android support, but I'm running into this error when importing `OAuthManager` on a fresh RN project:

```
'import' and 'export' may appear only with 'sourceType: module'
```

Sounds like a Babel issue maybe? It's an entirely fresh project, so it's just using the `react-native` preset. Do I need to add any extra configuration to get this to work?

**Comment by auser** [comment]
Weird. Can you push your source open-source? If not, I would be happy to hop on screenhero (can send you an invite if you need one)

**Comment by auser** [comment]
@naiyt I can't replicate this... I've updated the README and built it off a fresh project here... any more hints as to how/when you encountered this?

**Comment by naiyt** [comment]
Weird, tried again today and now I can't replicate it either. Clearly must have been a PEBKAC problem of some sort. =\ Sorry about that.
