### ISSUE TITLE
Unexpected behaviour in app with Login with Google after redirection from Safari

### ISSUE THREAD

**Issue by roshangm1** [fullstackreact/react-native-oauth#101]
I have implemented login with Facebook and Login with Google with this library in my app. Everything is working fine on Android. Both Facebook and Google.
Also, everything is fine with Facebook on iOS.
But there are couple of issues with Login with Google on iOS. Here is what's happening

When logging with google for the first time, i can do get everything i need on safari and after logging in there, I can redirect to my app too but the behaviour in the app is unexpected (nothing happens), while with Facebook, app gets data and certain code are executed.

After then when I try logging in again with Google, i get these warnings on my terminal:
```
 <Warning>: Ignoring credentials key: hash
 <Warning>: Ignoring credentials key: superclass
<Warning>: Ignoring credentials key: description
 Ignoring credentials key: debugDescription
```

This is the way, I am implementing Login with Google in my code:
```
loginWithGoogle = () => {
    manager.authorize('google', {scopes: 'email'})
      .then((resp) => {
        if(resp.authorized) {
          console.log('Hello');
          manager.makeRequest('google','https://www.googleapis.com/plus/v1/people/me')
            .then(resp => {
              console.log(resp);
              if (resp.status === 200) {
                  this.registerUser(resp.data.displayName,'',resp.data.emails[0].value, "password", "google",resp.data.id)
                // this.props.nav.push({ name: 'locations', background: 'purple'})
              }
            })
            .catch(error => {
              console.error(error);
              console.log('ERrorrorororo');
            });
          }
        })
      .catch(err => {
        console.error(err);
        console.log("aaaaaeroro");
      });

  }
```

**Comment by roshangm1** [comment]
I had this issue while parsing the response. There is different form of responses in iOS and Android.

**Comment by Puvvl** [comment]
I have some issues, what did u do?
