### ISSUE TITLE
RCTLinkingManager.h file not found error in OAuthManager.h file

### ISSUE THREAD

**Issue by Vjsharma** [fullstackreact/react-native-oauth#12]
Hi All,

I have followed all the steps to integrate react-native-auth from latest README file. But I am getting linking error(RCTLinkingManager.h file not found error in OAuthManager.h) when importing OAuthManager.h in app delegate at runtime.

I am not able to run the app.

**Comment by Vjsharma** [comment]
I think it is the same as #12

**Comment by cjmartin** [comment]
I had to manually link `node_modules/react-native/Libraries/LinkingIOS/` following the instructions here: https://facebook.github.io/react-native/docs/linking-libraries-ios.html

Including step 3.

**Comment by cjmartin** [comment]
I also had the issue in #8, I had to do step 2 in the linking instructions manually for OAuthManager as well.

**Comment by auser** [comment]
I'll take a look at this with a new app and update the README instructions to reflect.

**Comment by auser** [comment]
@cjmartin @Vjsharma Check the latest README, it should address these issues.

**Comment by Vjsharma** [comment]
Thanks. I have resolved that one but now I am getting - #8

**Comment by auser** [comment]
Did you see the latest update to the readme about adding to headers?

**Comment by cjmartin** [comment]
Hi Ari, adding the headers is one piece, but I found I also needed to add libraries to another section in XCode (linking binaries under built settings I think, I'm not looking at it right now).

It might be extremely helpful to have a very basic example app that people could pull, npm install, fill in twitter app credentials, and run. Just to see everything working...

**Comment by auser** [comment]
There _is_ one: https://github.com/fullstackreact/FirestackApp

**Comment by cjmartin** [comment]
Nice, I'll give that a run and see if I hit any of the same issues I've seen starting from scratch. Thanks.
