### ISSUE TITLE
No recent npm release

### ISSUE THREAD

**Issue by vbuch** [fullstackreact/react-native-oauth#137]
@auser there have been quite some Merges you did (including some from me) but there is no recent update to the version in npm. Interesting enough, npm says the version is 2.1.16 which should be coming from the package.json but the master here is at 2.1.15 and the latest tag is 2.1.14.
Are you planning to update the version in npm soon?
Whoever is using the new features available in this repo needs to stay locked to the git repo instead of the official npm package. This was also mentioned in some issues that would get cloes when this is done.
Thank you for your time!

**Comment by auser** [comment]
Will push it up now.

**Comment by vbuch** [comment]
Thank you for 2.2.0!
