### ISSUE TITLE
Add documentation about security

### ISSUE THREAD

**Issue by NoelBroda** [fullstackreact/react-native-oauth#16]
Hi!
I recommend to add documentation about how much secure is to write SECRET TOKENS in React Native.

I'm pretty sure more people will use this module if you add more information about it.

And maybe you should answer this question: http://stackoverflow.com/questions/40637101/how-to-securely-store-secret-keys-on-react-native-client-side ;)

**Comment by auser** [comment]
@NoelBroda Thanks for the issue.

In `react-native-oauth`, we're not actually using RN to store the access_tokens, but a native store. Setting the client_id and client_secret could be done in a plist/json natively, however. This would be a good enhancement, IMHO.

**Comment by NoelBroda** [comment]
@auser To be honest, I really can not implement this library until get a really secure way to save the secret tokens. So, if you want, I can try to help you. Give me a couple of "keywords" to search in google about it, and I'll try to send a PR with it.
I have no idea about Objective-C, but, I can spend a couple of days looking for it

**Comment by auser** [comment]
It's not "insecure," per say to save keys in JS, but it definitely would be _more_ secure with them stored in compiled code rather than in JS. 

Objective-c: plists are pretty easy. Can probably add that tonight
Java: .json files shouldn't be difficult either. Can you make an issue for this to help me track?

**Comment by auser** [comment]
Actually, I lied... plists are already implemented for iOS 👍 
https://github.com/fullstackreact/react-native-oauth/blob/master/ios/OAuthManager/OAuthManager.m#L83
