### ISSUE TITLE
Safari cant open page because address is invalid

### ISSUE THREAD

**Issue by ajonno** [fullstackreact/react-native-oauth#17]
Any idea why this is showing after we enter credentials into Google ?

the config object for Google looks like this:
google: {
      callback_url: 'com.googleusercontent.apps.xxxxxxxxxxxxxx:/google',
      client_id: 'xxxxxxxxxmf.apps.googleusercontent.com'
   }

![image](https://cloud.githubusercontent.com/assets/3005269/20614024/c2c8c122-b31d-11e6-8746-c5deb5342247.png)

**Comment by NoelBroda** [comment]
You should use StackOverflow to ask this things

**Comment by auser** [comment]
You don't have a client_secret?

**Comment by ajonno** [comment]
actually the documentation here is a bit confusing. for example a client_secret is listed in a code snippet example at the very top of the README, but then later as part of the "Google" setup, it is not listed. that is important because a client_secret is provided when you setup a **WEB** application in the Google API Manager, whereas a client_secret is not given if you setup an iOS or Android client id. which should i be using ? im happy to submit a PR on the docs for this bit once ive got it working.

**Comment by pvogenthaler** [comment]
@ajonno I'm also finding the documentation confusing. The Credentials for Google **Web** application provides a Client ID and Client Secret (but not a URL Scheme/ Bundle ID) whereas the Credentials for Google **iOS** application provides only a Client ID and URL Scheme (and not the Client Secret). The documentation for Google auth setup seems to require the Client ID, URL Scheme, and Client Secret, however, neither the Credential provides all three. I'm curious if you (or anyone) was able to get this working. Thanks.

**Comment by adrianotadao** [comment]
In my case, I called `Facebook` on my URL SCHEMA and I was trying to call `facebook` on my `manager.authorize`.
