### ISSUE TITLE
Is this supposed to work for Android? Can't even build...

### ISSUE THREAD

**Issue by ujwal-setlur** [fullstackreact/react-native-oauth#19]
Hello,

I got this working for iOS (with minor difficulty, but it did work), but this does not even build for android:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.github.delight-im:Android-AdvancedWebView:v3.0.0.

Then I added 

maven { url "https://jitpack.io" }

to the android/build.gradle, so the package was found, but then I get a compilation error:

node_modules/react-native-oauth/android/src/main/java/io/fullstack/oauth/OAuthManagerModule.java:228: error: cannot find symbol
        OAuthRequest request = new OAuthRequest(httpVerb, url.toString(), service);

Any help? The reason I am looking at this package is that I need oAuth support for multiple providers on both iOS and Android.

Thanks...

**Comment by EyesBear** [comment]
Having the same issue here.

**Comment by auser** [comment]
Interesting. Yes, it should still work for Android. Can you provide a sample app?

**Comment by auser** [comment]
@EyesBear and @ujwal-setlur Can you try the latest version? I just pushed a new update to `npm`.

**Comment by auser** [comment]
Here is a react-native app that works on Android from:

```bash
react-native init authapp && cd authapp
yarn install
npm install --save react-native-oauth
react-native link react-native-oauth
react-native run-android
```

[http://d.pr/f/M9hT.tar.gz](http://d.pr/f/M9hT.tar.gz)

**Comment by adrianotadao** [comment]
I'm having the same problem here.

```bash
/Users/adrianotadao/personal/timekeeper-app/node_modules/react-native-oauth/android/src/main/java/io/fullstack/oauth/OAuthManagerFragmentController.java:32: error: cannot find symbol
import com.github.scribejava.core.exceptions.OAuthConnectionException;
                                            ^
  symbol:   class OAuthConnectionException
  location: package com.github.scribejava.core.exceptions
```

@ujwal-setlur how did you fix it? Could you please share your solution?

**Comment by auser** [comment]
You need to add 

```
 maven { url "https://jitpack.io" }
```

to your `build.gradle`

**Comment by adrianotadao** [comment]
@auser I added and then, I received this error 😢 

Before adding this `mave`, I received the error:

```
Could not resolve all dependencies for configuration ':app:_debugCompile'.
Could not find com.github.delight-im:Android-AdvancedWebView:v3.0.0.
```

**Comment by ujwal-setlur** [comment]
That's the error I got as well I believe

Get Outlook for iOS




On Wed, Jan 18, 2017 at 4:21 PM -0800, "Adriano Tadao" <notifications@github.com> wrote:












@auser I added and then, I received this error 😢


Before adding this mave, I received the error:
Could not resolve all dependencies for configuration ':app:_debugCompile'.
Could not find com.github.delight-im:Android-AdvancedWebView:v3.0.0.

**Comment by ujwal-setlur** [comment]
I will check out the latest version. Thanks

**Comment by ahmedu007** [comment]
Followed the instructions, Added the maven link still get an error: 

`> Task :react-native-oauth:compileReleaseJavaWithJavac
/Users/umair/Desktop/Projects/reactcore/node_modules/react-native-oauth/android/src/main/java/io/fullstack/oauth/OAuthManagerPackage.java:39: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/umair/Desktop/Projects/reactcore/node_modules/react-native-oauth/android/src/main/java/io/fullstack/oauth/OAuthManagerDialogFragment.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error`

Any help would be appreciated

**Comment by nokite** [comment]
My project also can't resolve AdvancedWebView. 
I see it as a dependency when I check the gradleDependencies:
+--- com.github.delight-im:Android-AdvancedWebView:v3.0.0@aar
But I don't see it listed in the external libraries. And consequently it can't be referenced in code.

**Comment by rincethomas** [comment]
Hi,
  I am getting error - Could not find com.github.delight-im:Android-AdvancedWebView:v3.0.0.

Any Solutions ?.

**Comment by vamsipidugu** [comment]
add
maven { url "https://jitpack.io" }

inside allprojects repositories and try

**Comment by Andrfas** [comment]
Facing an error
`Could not download Android-AdvancedWebView.aar (com.github.delight-im:Android-AdvancedWebView:v3.0.0): Skipped due to earlier error`

Already added `maven { url "https://jitpack.io" }`.
Did anyone solve this issue?
