### ISSUE TITLE
App crash on vanilla install - `LICreateIconForImage passed NULL CGImageRef image`

### ISSUE THREAD

**Issue by Oblongmana** [fullstackreact/react-native-oauth#2]
# Environment
react-native-cli version: 1.0.0
react-native version: 0.31.0
OS: Mac OSX, El Capitan 10.11.6
XCode Version: 7.3.1

# Issue/Repro
1. Create a new React Native project
2. `npm install --save react-native-oauth`
3. `rnpm link` (per README instructions), or `react-native link` (it's in react-native core now)
4. `react-native run-ios`
5. Observe that the build appears to run fine, but that the app is not open in simulator
6. `react-native log-ios`
7. Attempt to open the app in simulator
8. Observe that it immediately crashes to desktop, and the following is dumped to the log window (see step 6)
```
Aug 14 05:15:42 103-246-99-69 assertiond[27930] <Error>: assertion failed: 15G31 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Aug 14 05:15:42 103-246-99-69 Unknown[27930] <Error>: 
Aug 14 05:15:42 103-246-99-69 com.apple.CoreSimulator.SimDevice.FF100908-C6A2-4AAA-B129-282E74451653.launchd_sim[27910] (UIKitApplication:org.reactjs.native.example.TestProject[0x54a8][30249]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
Aug 14 05:15:43 103-246-99-69 SpringBoard[27926] <Warning>: LICreateIconForImage passed NULL CGImageRef image
Aug 14 05:15:43 103-246-99-69 SpringBoard[27926] <Warning>: Application 'UIKitApplication:org.reactjs.native.example.TestProject[0x54a8]' crashed.
Aug 14 05:15:43 103-246-99-69 assertiond[27930] <Error>: assertion failed: 15G31 13E230: assertiond + 15801 [3C808658-78EC-3950-A264-79A64E0E463B]: 0x1
Aug 14 05:15:43 103-246-99-69 Unknown[27930] <Error>: 
Aug 14 05:15:43 103-246-99-69 SpringBoard[27926] <Warning>: Reply Error: Connection interrupted
```

# Other Comments
This is all without doing anything further, no references to the library or anything, just a 100% fresh new react native project, with this library added

A cursory google turns up the following: http://stackoverflow.com/questions/28126120/ios-8-app-crash-on-launch-licreateiconforimage-passed-null-cgimageref-image

That includes a link to another question, supposedly solving the first one: http://stackoverflow.com/questions/24333981/ios-app-with-framework-crashed-on-device-dyld-library-not-loaded-xcode-6-beta

Gets a bit beyond me at that point, but I'm thinking if there are additional steps needed, it might be worth documenting them in the README? Apologies if I'm making any noobie mistakes here!

**Comment by Oblongmana** [comment]
I wondered if it might be an issue with what was published to `npm`, as I noticed the npm version is 1.0.7, while the most recent "version" commit in your history is "1.0.6" (no git tags on github at the moment, might not be pushed?). 

The version NPM installs is this commit: https://github.com/fullstackreact/react-native-oauth/commit/414ed32081133c4ced7b8d205ff5c0efbee0b30f - "WIP Swift"

I did change my package.json to point to the current HEAD (`"react-native-oauth": "https://github.com/fullstackreact/react-native-oauth.git#b78232c731ba4d2cfb0cfd0fb4a8aff494dc4898"`), but the issue above remains

**Comment by kont-noor** [comment]
I get the same issue

**Comment by auser** [comment]
Yep, I have a big update coming on the `feature/dctauth` branch that I'll merge when I finish Google auth.

**Comment by auser** [comment]
I have updated this completely and released a new version. Please pull the latest.

The README has been updated as well.
