### ISSUE TITLE
Undefined symbols for architecture arm64 / Does not contain bitcode  (iOS)

### ISSUE THREAD

**Issue by serranoarevalo** [fullstackreact/react-native-oauth#20]
I'm getting the following error, when I try to build:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_OAuthManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I think I have followed the tutorial and have done everything as it says. Any ideas of how can I solve this??

**Comment by serranoarevalo** [comment]
Okay so I fixed with this (https://github.com/fullstackreact/react-native-oauth/issues/13) but now I'm getting 

`Build/Products/Debug-iphoneos/libOAuthManager.a(OAuthClient.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by smkhalsa** [comment]
I was running into the same issue, getting a `Linker command failed` error when I tried to build my XCode project. 

Here's what worked for me...

1. click on the OAuthManager.xcodeproj under Libraries
2. go to Build Settings
3. change "Enable Bitcode" to "Yes"
4. change the scheme from {my project} to "OAuthManager"
5. re-build the OAuthManager by going to the Product -> Build
6. change the scheme back to {my project}
7. Product -> Clean
8. Product -> Build
