### ISSUE TITLE
[iOS] Twitter Authorize Gives Error

### ISSUE THREAD

**Issue by cihancil** [fullstackreact/react-native-oauth#21]
I did every step on readme. I get this error

Possible Unhandled Promise Rejection (id: 0):
Cannot read property 'configureProvider' of undefined
TypeError: Cannot read property 'configureProvider' of undefined

**Comment by smkhalsa** [comment]
I'm getting this same error using facebook on iOS

**Comment by smkhalsa** [comment]
It looks like it's working for me now after I re-built the debug config scheme in XCode and re-ran on simulator

**Comment by auser** [comment]
Did you link `react-native-oauth` to your project?

**Comment by auser** [comment]
@cihancil and @smkhalsa ^^
