### ISSUE TITLE
215 Bad Authentication data

### ISSUE THREAD

**Issue by melihmucuk** [fullstackreact/react-native-oauth#22]
Hi, I'm getting "Bad authentication data" error from twitter. Here is my code:

```javascript
componentWillMount(){
    const home_timeline = 'https://api.twitter.com/1.1/statuses/home_timeline.json';

    manager.authorize('twitter')
    .then(resp => {
      if(resp.response.authorized){
        console.log(resp);
        manager.makeRequest('twitter', home_timeline)
        .then(resp => {
            console.log('Data ->', resp.data);
          });
      }
    })
    .catch(err => console.log(err));
  }
```

here is my logs: 

![screen shot 2016-12-06 at 19 39 20](https://cloud.githubusercontent.com/assets/3147488/20934313/5d66221a-bbe3-11e6-91a3-0c307acea138.png)

**Comment by shohey1226** [comment]
This happens to me.  I could get the token but not the feeds.

```
Xcode Version 8.1 (8B62)
react-native: 0.38.0
```

**Comment by auser** [comment]
@melihmucuk what platform are you running on?

**Comment by melihmucuk** [comment]
@auser ios 10 & MacOSX

**Comment by auser** [comment]
Okay, I discovered the issue. You need to enable keychain sharing in capabilities. I'll have to update the README for iOS.

http://d.pr/i/G86D.png

Can you update your capabilities and see if that fixes it?

**Comment by melihmucuk** [comment]
thanks @auser now it works !
