### ISSUE TITLE
Error on get > Cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by julesmoretti** [fullstackreact/react-native-oauth#23]
I am trying to retrieve some user data but unfortunately I am getting error.

I am able to authenticate and get a user token but not make a request. So what am I missing please?

Thank you.

```
manager
	.makeRequest('google', 'https://www.googleapis.com/oauth2/v1/userinfo')
	.then(resp => {
		console.log('Data ->', resp.data);
	})
	.catch(err => console.log(err));
```

<img width="1146" alt="screen shot 2016-12-12 at 5 35 38 pm" src="https://cloud.githubusercontent.com/assets/744300/21124053/6f2f62b0-c091-11e6-8546-9f8212075a30.png">

**Comment by auser** [comment]
Yikes! Just encountered this issue. Looking.

**Comment by auser** [comment]
Found it and pushed a fix to `master`. Will push to a new `npm`

**Comment by julesmoretti** [comment]
sweet thank you :)
