### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid Api secret

### ISSUE THREAD

**Issue by northern-fox** [fullstackreact/react-native-oauth#25]
I'm creating a facebook app (https://developers.facebook.com)
This is my code:
```
import OAuthManager from 'react-native-oauth';
const manager = new OAuthManager('test');
manager.configure({
        facebook: {
		client_id: 'xxxx',          //Application ID
		client_Secret: 'xxxxxxxx'   //App secret
	}
});
manager.authorize('facebook')
.then(resp => console.log(resp, 'Your users ID'))
.catch(err => console.log(err, 'There was an error'));
```
And I have this error:

allErrorMessage: "java.lang.IllegalArgumentException: Invalid Api secret"
errorMessage: "Invalid Api secret"

Any help please ?

**Comment by auser** [comment]
Hey @northern-fox 

I just pushed a small update to the npm module that fixes that over here. Can you try and see if it fixes it on your end?

**Comment by northern-fox** [comment]
Hi @auser 

Your update resolved my another issue, but I get the error yet

**Comment by auser** [comment]
Make sure you copied the complete strings without while space

**Comment by northern-fox** [comment]
@auser, I changed **client_Secret** key to **client_secret** now it's works.
