### ISSUE TITLE
Open external browser rather than InApp browser

### ISSUE THREAD

**Issue by pewh** [fullstackreact/react-native-oauth#27]
Hello. Thanks for create this repo.

My use-case for this repo is consume OAuth for Google. It seems this repo use InApp browser (or embedded browser), which unfortunately Google [will deprecate](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html) embedded browser OAuth. It will show warning like below.

![](https://cloud.githubusercontent.com/assets/239360/21267817/4c2fb814-c3ac-11e6-83cf-52eb5a36d668.png)

One of the recommended ways is open new browser for `OAuth`-ing rather than on embedded browser. So, any idea for it? Thanks :beers:

**Comment by brunolemos** [comment]
@pewh at the end of the article you posted:

> On November 1, we added a notification on our consent page alerting developers of this deprecation. Developers can acknowledge the deprecation and remove this notice from the consent page by including a URL parameter "**suppress_webview_warning=true**" in the request.

So it's a temporary workaround until a real solution.

**Comment by pewh** [comment]
@brunolemos how to include that URL parameter in `react-native-oauth`? I can't figure out what file need to change. Thanks

**Comment by pewh** [comment]
It seems I need to change https://github.com/fullstackreact/react-native-oauth/blob/master/lib/authProviders.js#L48-L54 into
```
  'google': {
    auth_version: "2.0",
    authorize_url: 'https://accounts.google.com/o/oauth2/auth?suppress_webview_warning=true',
    access_token_url: 'https://accounts.google.com/o/oauth2/token'?suppress_webview_warning=true,
    callback_url: ({app_name}) => `${app_name}://oauth-response`,
    validate: validate()
  },
```

Let me to testing first.

**Comment by auser** [comment]
Can you make a PR, @pewh

**Comment by auser** [comment]
@pewh Alternatively, can you add this to the README?
