### ISSUE TITLE
dyld: Library not loaded 

### ISSUE THREAD

**Issue by ariaz** [fullstackreact/react-native-oauth#3]
This occurs when deploying / debugging in device (works fine in Simulator). If this is the general case, could you update your setup guides?

dyld: Library not loaded: .../Xcode/DerivedData/MyApp-ladsjflkdskjflsdjfkkdl/Build/Products/Debug-iphoneos/libOAuthManager.a
  Referenced from: /var/containers/Bundle/Application/.../MyApp.app/App
  Reason: image not found

Thank you,

-Ariel

**Comment by auser** [comment]
Yep, I have a big update coming on the `feature/dctauth` branch that I'll merge when I finish Google auth.

**Comment by auser** [comment]
I have updated this completely and released a new version. Please pull the latest.

The README has been updated as well.
