### ISSUE TITLE
Instagram support?

### ISSUE THREAD

**Issue by Vikaton** [fullstackreact/react-native-oauth#30]
Is Instagram support something that is coming soon?

**Comment by auser** [comment]
Possibly. Should be relatively straight-forward. You might be able to add it just by updating the `lib/authProviders.js` file... try it?

**Comment by auser** [comment]
Okay, so it looks like Instagram requires some serious work to get it working. 

Reason: Instagram does not support (as far as I can tell) custom, non http redirect urls. To support instgram, we'll have to change the way we do authorization with an in-app browser. 

Open to PRs.

**Comment by Vikaton** [comment]
The way I combated this was when I was using `react-native-instagram-oauth`, I had my redirect URI go to my website passing the auth token, which then redirected to the custom url scheme. Not sure if that can help with anything regarding this.

**Comment by auser** [comment]
Yep, that's the server-side flow. It's more secure, but not a universal fix for the library.

**Comment by Aaronius** [comment]
I'd still like to see this implemented. I'm a fresh noob to oath or I would take a stab at it myself.
