### ISSUE TITLE
Not working on android device

### ISSUE THREAD

**Issue by grzegorzhauska** [fullstackreact/react-native-oauth#31]
I have a hard time debugging why `manager.authorize('facebook')` call never resolves for me on a device while working on emulator.

```
login_facebook() {
const config = {
  facebook: {
    client_id: '****',
    client_secret: '****'
  }
}
const manager = new OAuthManager('***dev');
manager.configure(config);

console.log('one');
manager.authorize('facebook')
       .then(data => {
          console.log('two');
          console.log(data);
       })
       .catch(err => {
          console.log('three');
          console.log(err)
       });

}
```

adb -s device_id logcat | grep -E 'ReactNativeJS|OAuthManager'

```
I/OAuthManager(28552): configureProvider for facebook
I/ReactNativeJS(28552): one
```

A small white dialog box appears. Any pointers how to get it working?

I asked also on SO: http://stackoverflow.com/questions/41272204/how-to-fix-oauthmanager-authorize-call-on-android-device

**Comment by grzegorzhauska** [comment]
My mistake, authorization is working ok

**Comment by seanwilkening** [comment]
What was your issue?  I am having the same thing happen as well.
