### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by AlisonWonderlandApps** [fullstackreact/react-native-oauth#32]
sigh this module NEVER loads for me. I'm aware its not an oauth issue, but I cannot find an answer to this issue.
I just get Setting up CocoaPods master repo.....  never ends.
Honestly this is just too hard to setup. I think its almost easier to just do it manually.

**Comment by auser** [comment]
What is the actual error?

**Comment by Monte9** [comment]
@auser Running into the same issue. When using rnpm to link the outh library using `react-native link react-native-oauth` it displays the following: 
```
Preparing to link react-native-firestack for iOS
Checking CocoaPods...
CocoaPods already installed
rnpm-install info Linking react-native-oauth android dependency 
rnpm-install info Android module react-native-oauth has been successfully linked 
rnpm-install info Linking react-native-oauth ios dependency 
rnpm-install info iOS module react-native-oauth has been successfully linked 
Checking Podfile in iOS project (/Users/montethakkar/developer/projects/react-native/react-native-social-starter/SocialStarter/ios/Podfile)
Adding Podfile to iOS project
Installing Pods
Setting up CocoaPods master repo
```
And then it just never finishes setting up the pod file. Any help would be much appreaciated!

**Comment by Monte9** [comment]
Also my pod file looks like this (if it helps you debug the issue):
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialStarter

  target 'SocialStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
```
/cc @auser

**Comment by somlor** [comment]
Seeing same thing on my end as well. Happy to provide more details or help however I can.

**Comment by Monte9** [comment]
SOLVED! 
Go to `~/.cocoapods/repos` and run `git clone https://github.com/CocoaPods/Specs.git master`
Once you are done with that, run `react-native link` again. If it fails this time with the error: `throw new Error(`Error occured during executing "${ command }" command`);` then `gem install cocoapods`
/cc @AlisonWonderlandApps @somlor

**Comment by AlisonWonderlandApps** [comment]
Hi I found the answer is just that cocoapods is a massive file that actually does take forever :/ 
This gave more clarity:
http://stackoverflow.com/questions/21022638/pod-install-is-staying-on-setting-up-cocoapods-master-repo

Hope this helps someone else!
