### ISSUE TITLE
Unable to authenticate Twitter; OAuthManager does not print resp object 

### ISSUE THREAD

**Issue by Monte9** [fullstackreact/react-native-oauth#33]
```js
authenticateTwitterLogin() {
    manager.authorize('twitter', {scopes: 'profile,email'})
      .then(resp => console.log(resp))
      .catch(err => console.log(err));
  }
```
I am trying to authenticate Twitter with the above code; It opens the twitter login in Safari; upon successful authentication, it asks me to redirect me back to my app `SocialStarter` and then it does not print/console.log anything. 

From what I understand, it should handle the promise and `console.log(resp)` above, right? It does not do so. 

Also if it helps, in my xcode logs I see the following: 
```
called clearPendingAccount: <DCTOAuth1Account: 0x60800032a5a0; type = twitter; identifier = ACFD6CCE-B0A2-4543-B099-EA4EBCB31CDE; credential = (null)>
```
Any help is much appreciated. Thanks.

**Comment by auser** [comment]
Can you upgrade to the latest version? I fixed this with the latest version.

In addition, you need to make sure that you have shared preferences enabled on your project. The credentials/secrets are stored in your user preferences, so without access to the preferences, the `credentials` object will always be `(null)`. The latest version (on github and npm) should resolve this issue.

**Comment by BrendanBerkley** [comment]
> you need to make sure that you have shared preferences enabled on your project

What is this, and how do I do it? Didn't see any reference to "preferences" in this project's docs. I'm not sure what I'm searching for here either. Something like [this](https://stackoverflow.com/questions/19206762/equivalent-to-shared-preferences-in-ios)?
