### ISSUE TITLE
client_secret in code

### ISSUE THREAD

**Issue by tizzyapunkt** [fullstackreact/react-native-oauth#34]
Hi Ari,

i am new to the oAuth topic and it's nice that you created that lib. one thing i was wondering about is that i have to put the client_secret in the code that runs on the device. 
in a lot of articles and videos on the authorization code grant flow, they said that the client_secret should stay on the server.

do i miss something? 

best
tizian

**Comment by scstan** [comment]
then just put it on the server and config OAuth on demand getting the secret before manager.authorize('stuff').

**Comment by auser** [comment]
Alternatively, you can bundle it in compiled code. For iOS, you can do this in a file called `OAuthManager.plist` with the same contents as the JS code (reference: https://github.com/fullstackreact/react-native-oauth/blob/master/ios/OAuthManager/OAuthManager.m#L92)

I haven't implemented this same behavior (yet) for Android.
