### ISSUE TITLE
Slack for Android?

### ISSUE THREAD

**Issue by akondo06** [fullstackreact/react-native-oauth#38]
Hi, was just wondering if/when slack for android will be supported?
And/or microsoft support?

Thanks.

**Comment by auser** [comment]
PRs gladly accepted :)

(The goal is to get it to be supported: https://github.com/OvertimeNZ/scribe-slack-api/blob/master/src/test/java/nz/overtime/oauth/examples/SlackExample.java)

**Comment by auser** [comment]
Okay, I ended up implementing it for Android. :)
