### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by waleedarshad-vf** [fullstackreact/react-native-oauth#4]
Anybody working for android support?

**Comment by waleedarshad-vf** [comment]
+1

**Comment by auser** [comment]
Not yet... I have been focusing on `react-native-firestack` for the time being. If you want to contribute, I'd be glad to accept PRs. 

It's on the TODO list, but not the most immediate focus :/.

**Comment by auser** [comment]
Will do soon.

**Comment by naiyt** [comment]
@auser are you currently working on Android support? If not, I may take a stab at it, since I'm in need of a good outh library for RN Android.

**Comment by auser** [comment]
That would be awesome. If you can match the JS API, that would be the best. I had started it, but between traveling and the flu, I haven't been back at it. 

Important needs to match the iOS side:

Oauth v1/2 support, with the key being the provider. Check out how the iOS side is implemented for more details on what I mean. 

I can also hop in the gitter room a bit later if you'd like to discuss in realtime.

**Comment by naiyt** [comment]
Cool, I'll hop in the gitter room.

**Comment by naiyt** [comment]
I actually don't see a gitter room for react-native-oauth -- were you going to make one?

**Comment by auser** [comment]
Oh join the firestack one. I'll update the readme with a link

**Comment by naiyt** [comment]
So I started a bit of preliminary work on implementing a bridge to an existing Android OAuth library (https://github.com/wuman/android-oauth-client) but ran into some issues. I ended up going with an ad-hoc approach of sorts for my app instead, as I didn't really need a full OAuth solution yet (just an Oauth 2 authorization flow for one of my own applications).

Because of that I'm not sure when I'll be able to get back to helping out with Android support in this library. If someone else wants to pick up on it instead, that would be cool. If not, I may return to it later on.

**Comment by ajonno** [comment]
gday Ari - first a HUGE thanks for all your work with Firestack, and now this OAuth lib. We're implementing an Aust. govt funded app right now and using both. Your a genuine legend.

Do you think Android support is something that could be done in say next few weeks ? I know I'm 'asking' and not 'giving back' which i want to do one day for you (Android isn't my forte). Appreciate if u can let me know ? cheers.

**Comment by auser** [comment]
@ajonno I've started the Android implementation today and I've only started working on it for `twitter`. I'll push this work up to the `feature/android` branch, if you want to continue the implementation.

* `configureProvider` is implemented
* `authorize` is implemented
* `savedAccount`/`savedAccounts` method implemented
* `deauthorize` is implemented
* `makeRequest` is _not_ implemented

The rest of the work is really just getting the `makeRequest` and `2.0` providers working.

**Comment by auser** [comment]
Alright, I simplified a LOT of the code and am using a different backing library with a more permissible license (and it's way nicer). In any case, I have pretty much everything implemented for Android (except not Google auth yet). Other than google Auth (which shouldn't be too hard), feel free to test it from the `feature/android` branch.

**Comment by ajonno** [comment]
thats great thanks Ari. ill definitely look at testing and if i can get time help with adding Google for android. i'm still struggling to get Google iOS auth working with Firebase (Firestack signInWithProvider() call fails when I use the access_token) so that has to be my current priority.

**Comment by auser** [comment]
@ajonno Added Google auth support to the branch.

**Comment by ajonno** [comment]
cool ill take a look

**Comment by auser** [comment]
Alright, both Android and iOS are supported. My task list before I can close this issue:

[x] Google auth
[x] Github
[x] Facebook
[x] Twitter
[ ] Documentation
