### ISSUE TITLE
manage.authorize promise is not resolved or rejected

### ISSUE THREAD

**Issue by Aaronius** [fullstackreact/react-native-oauth#41]
I followed the readme except for when I enabled Keychain Sharing Entitlement in Capabilities I got an error icon next to "Add the Keychain Sharing feature to your App ID" and a message under it saying "Failed to create provisioning profile". Anyway, I was (possibly incorrectly) hoping I could ignore it and see if I could get further into my prototype. I got the rest of the setup done but when my code executes `manager.authorize`, the resulting promise never gets resolved or rejected. I don't get any kind of error in the debugging console and I don't see requests go to Twitter in the network tab.

My code looks like this:

```
const manager = new OAuthManager('peoplewatch');
    manager.configure(config);
    manager.authorize('twitter')
      .then((response) => {
        console.log(response);
      })
      .catch((err) => {
        console.log(err);
      });
```

I tried debugging deeper into the `authorize` code but it got to where it queues up the call to the native code and lost me after that. Could this be a bug or am I missing something? Thanks!

**Comment by auser** [comment]
Yes, what version are you using? Try passing a second argument. Does that fix it?

**Comment by Aaronius** [comment]
I was trying with 2.1.11. I just tried 2.1.13 with and without a second argument and the promise is still not resolved or rejected. I'm not sure what to pass as a second argument though. I just passed an empty object.

**Comment by woomike** [comment]
I'm having the same issue but with Google Oauth.  I am able to allow access to the app, but google does not redirect me back into the app and the promise never resolves.

**Comment by FrenchBully** [comment]
I was able to get it working for Google.  Looks like the only scope I'm able to pass is 'email'. The url to pass as an argument for manager.makeRequest is 'https://www.googleapis.com/plus/v1/people/me'

**Comment by auser** [comment]
Closing in favor of #42. You need to make sure you have the app set up properly. I'll add a checklist on the README to discuss this.
