### ISSUE TITLE
OAuthManager.h file not found

### ISSUE THREAD

**Issue by neuberoliveira** [fullstackreact/react-native-oauth#45]
I did all steps for configuring IOS app, the only problem is this message:
Lexical os Preprocessor Issue
    OAuthManager.h file not found

![captura de tela 2017-01-17 as 13 49 14](https://cloud.githubusercontent.com/assets/3378304/22028606/e5c98114-dcbe-11e6-83c6-258aed297b56.png)

To me seems the file exists in the project, but somehow xcode wont find it.

The OAuth lib is linked too.
![captura de tela 2017-01-17 as 13 50 38](https://cloud.githubusercontent.com/assets/3378304/22028676/1e330ff2-dcbf-11e6-871a-3951e35ef224.png)

What could it be?

**Comment by TomAtterton** [comment]
Make sure that you have `$(SRCROOT)/../node_modules/react-native-oauth/ios/OAuthManager` in your header search paths.

**Comment by auser** [comment]
Updated the README with this link

**Comment by neuberoliveira** [comment]
Its working now thanks

**Comment by jsbranco** [comment]
I am still facing this issue after adding it to the header search paths, I installed react-native-oauth and followed the linking steps :
![screen shot 2017-02-06 at 1 17 49 am](https://cloud.githubusercontent.com/assets/11029783/22628163/2a520392-ec0a-11e6-92e0-7a67429772af.png)

What might I have missed :/ ?
