### ISSUE TITLE
AppDelegate.m error: use of undeclared identifier 'OAuthManager'

### ISSUE THREAD

**Issue by marclundgren** [fullstackreact/react-native-oauth#6]
hi,

After following both the automatic ios setup, and the manual one, I'm seeing this error when attempting to build the project. 

Am I supposed to be importing `OAuthManager` somewhere in `AppDelegate.m`? Or is it supposed to be a global reference?

```
/TwitterExample/AppDelegate.m:40:11: error: use of undeclared identifier 'OAuthManager'
  return [OAuthManager handleOpenUrl:application openURL:url sourceApplication:sourceApplication annotation:annotation];
          ^
1 error generated.

** BUILD FAILED **


The following build commands failed:
       	CompileC build/Build/Intermediates/TwitterExample.build/Debug-iphonesimulator/TwitterExample.build/Objects-normal/x86_64/AppDelegate.o TwitterExample/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by pughpugh** [comment]
I believe you need `#import "OAuthManager.h"` at the top of `AppDelegate.m`.

**Comment by auser** [comment]
Yep, I have a big update coming on the `feature/dctauth` branch that I'll merge when I finish Google auth.

**Comment by auser** [comment]
I have updated this completely and released a new version. Please pull the latest.

The README has been updated as well.
