### ISSUE TITLE
Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by jojonarte** [fullstackreact/react-native-oauth#7]
The xcode prompts that the library requires converting to swift 3, I tried converting but to no avail the code still crashes when running.

**Comment by auser** [comment]
Yep, I have a big update coming on the `feature/dctauth` branch that I'll merge when I finish Google auth.

**Comment by jojonarte** [comment]
cool to hear bro.

**Comment by auser** [comment]
I have updated this completely and released a new version. Please pull the latest.

The README has been updated as well.
