### ISSUE TITLE
Facebook auth screen not displayed well

### ISSUE THREAD

**Issue by adrianha** [fullstackreact/react-native-oauth#73]
Hi,
I found that facebook login not displaying well on my device (Sony Xperia Z3 Compact).
Here's image attached: 
![242](https://cloud.githubusercontent.com/assets/5382429/22914893/eb399ce0-f2a5-11e6-8aff-69ffb02ede35.jpg)
How do i resolve this problem?
Thanks

**Comment by StasDoskalenko** [comment]
Hi! I've encountered the same issue!
