### ISSUE TITLE
Deauthorize facebook oauth

### ISSUE THREAD

**Issue by adrianha** [fullstackreact/react-native-oauth#74]
Hi,
I'm facing an issue when i already deauthorized facebook login and then i try to do authorization again, i will be logged in automatically as last previous authorized account. Is there any solution how to force user to input email & password again?
Thank you

**Comment by andreeapescar** [comment]
Any solutions?

**Comment by adrianha** [comment]
Dont have any solution for now. Currently using react-native-fbsdk

**Comment by MrGru** [comment]
The same problem with facebook and google login, Cannot login other accounts

**Comment by IlifilzaRusli** [comment]
Any solution? Still having the same issue

**Comment by thecodecafe** [comment]
I'm having a problem please, can someone help me, whenever I log into my social media account, for some unknown reason, I can't login with a different account, every time i click on authorise, skips the consent screen and just logs the person in, is there a way to make such that the user can actually choose to login with a different social media or google account?
