### ISSUE TITLE
Undefined error when invoking OAuthManager constructor with app name

### ISSUE THREAD

**Issue by msciotti** [fullstackreact/react-native-oauth#75]
Going through the example, the following code throws the error: `undefined is not a constructor(evaluating 'new _reactNativeOauth.OAuthManager`:

```
import { OAuthManager } from 'react-native-oauth';
const manager = new OAuthManager('RedFish')
manager.configure({
  facebook:{
    client_id: 'MY_ID',
    client_secret: 'MY_SECRET'
  }
});
```

Stack trace - apologies for the poor format. Couldn't copy/paste:

![image](https://cloud.githubusercontent.com/assets/4193854/23040895/0f2d66ec-f461-11e6-9fc1-622170c8891e.png)

![image](https://cloud.githubusercontent.com/assets/4193854/23040913/29f47146-f461-11e6-88d5-1530c3e37b51.png)

![image](https://cloud.githubusercontent.com/assets/4193854/23040923/3362cd9a-f461-11e6-9ffa-9c0732429e9a.png)

**Comment by msciotti** [comment]
My issue was that the import line should read `import OAuthManager from 'react-native-oauth';` I'm new to react; apparently the braces make all the difference. Apologies!

**Comment by chenshuiluke** [comment]
@msciotti Thanks, your solution really helped
