### ISSUE TITLE
Build Failed with Linking Error

### ISSUE THREAD

**Issue by Talkwondo** [fullstackreact/react-native-oauth#8]
Hi,
I have installed the pods everything looks good as you instructions, but i get an error i can not fix:
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_OAuthManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

i tried to link several times with rnpm. this is does not

**Comment by auser** [comment]
I have updated this completely and released a new version. Please pull the latest.

The README has been updated as well.

**Comment by matt-d-rat** [comment]
I am getting the same error as reported 25 days ago. I have only just started using this library yesterday, so I'm not sure what I am doing wrong as I have followed all of the instructions listed in the README as far as I can tell...
