### ISSUE TITLE
Update npm version to add 'addProvider' function

### ISSUE THREAD

**Issue by MeisterTea** [fullstackreact/react-native-oauth#80]
Hi, it seems the npm version is missing the latests commits.

Could you push it so we can use the latest functions with npm ?

I am looking to integrate linkedin with it.

Regards

**Comment by vbuch** [comment]
@auser how about a release soon? Relying on branches/master is not cool. :-)

**Comment by vbuch** [comment]
@0is1, you may roll that commit back now :-) [2.2.0](https://github.com/fullstackreact/react-native-oauth/issues/137#issuecomment-320729712) is in npm and this issue is done.
