### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_DCTAuth", referenced from:       objc-class-ref in libOAuthManager.a(OAuthManager-9417F9659D89048A.o)

### ISSUE THREAD

**Issue by scstan** [fullstackreact/react-native-oauth#81]
I keep getting this error and I can't run the app.

error: http://snpy.in/tZZVLH
podfile: http://snpy.in/tBnpnb
pod installed: http://snpy.in/ygGTsW
linked binaries: http://snpy.in/Q04r3b

I searched through all other issues and tried to apply the fixes .. but it didn't help.

"react-native-oauth": "^2.1.16"
"react-native": "^0.41.2"

What can I do to fix this ?

**Comment by scstan** [comment]
Fixed it by linking DCTAuth to my apps test targets

**Comment by alfie-ab** [comment]
Hi @scstan, I have a similar error - could you elaborate on how you solved it? Thank you

**Comment by scstan** [comment]
In xcode: 
1. http://snpy.in/LkUxmF
2. http://snpy.in/uUbm5Q

**Comment by dotansimha** [comment]
@scstan 
I'm having the same issue here. so far I found out that after build phase, XCode created two `libReact.a` in my build dir...
