### ISSUE TITLE
Slack Support

### ISSUE THREAD

**Issue by adrianotadao** [fullstackreact/react-native-oauth#9]
Hello... I have a question, If I use it for the Slack provider, will it works?

**Comment by auser** [comment]
It should... it needs some testing, but I don't see why not.

**Comment by adrianotadao** [comment]
I agree with you. I'm very busy but I saw what you did and I think that will be easy to support Slack too

**Comment by auser** [comment]
@adrianotadao I added slack support for iOS. I haven't yet had the time to add it for Android, however!

**Comment by adrianotadao** [comment]
@auser very nice and thank you!
